#ifndef THATDISKCREATOR__DECL_H
#define THATDISKCREATOR__DECL_H

#define FAT_32_VOLUME_SIZE_MIN_MB 33ULL
#define FAT_32_VOLUME_SIZE_MIN_B (FAT_32_VOLUME_SIZE_MIN_MB << 20)
#define FAT_32_VOLUME_SIZE_MAX_GB 32ULL
#define FAT_32_VOLUME_SIZE_MAX_MB (FAT_32_VOLUME_SIZE_MAX_GB << 10)
#define FAT_32_VOLUME_SIZE_MAX_B (FAT_32_VOLUME_SIZE_MAX_MB << 20)
// TODO: add support for bigger disk sizes and hence cluster sizes
#define FAT_32_CLUSTER_SIZE_B 512

#define MBR_SIZE_B 512
#define GPT_HEADER_SIZE_B 92
// TODO: can be longer, min partition entries is 4
// TODO: replace GPT_LBA_COUNT with a variable
#define GPT_LBA_COUNT (1 + 32)
#define GPT_PARTITION_ARRAY_SIZE_B (16 << 10)
#define GPT_PARTITION_ARRAY_LENGTH 128
#define GPT_RESERVED_MB 1
#define GPT_RESERVED_B (GPT_RESERVED_MB << 20)

// TODO: add support 1024, 2048, 4096, etc
#define LOGICAL_BLOCK_SIZE_B 512

// TODO: determine minimum size: 33MB, e.g. 32MB (block size 512) + 1MB for MBR+GPT
#define DISK_SIZE_MIN_MB (FAT_32_VOLUME_SIZE_MIN_MB + GPT_RESERVED_MB)
#define DISK_SIZE_MIN_B (DISK_SIZE_MIN_MB << 20)

#define DISK_SIZE_MAX_MB (GPT_PARTITION_ARRAY_LENGTH * FAT_32_VOLUME_SIZE_MAX_MB + GPT_RESERVED_MB)
#define DISK_SIZE_MAX_B (DISK_SIZE_MAX_MB << 20)

#endif //THATDISKCREATOR__DECL_H
